### ISSUE TITLE
Inverted color swatches

### ISSUE THREAD

**Issue by Mottie** [RaitaroH/Stylus-DeepDark#1]
Awesome style!

With the addition of the colorpicker in the latest version, I've found the following definition inverts the swatch when a keyword is used:

```css
.cm-s-default span.cm-link, .cm-s-default span.cm-keyword {
  color: var(--main-color);
  filter: invert(100%);
}
```

![](https://user-images.githubusercontent.com/136959/33133693-295f0fec-cf63-11e7-9f1b-c62315b57a3d.png)

The screenshot is from using this css:

```css
@-moz-document domain("example.com") {
    body {
      color: red;
      background-color: white;
      border-color: orange;
    }
}
```

**Comment by RaitaroH** [comment]
I actually noticed. I will fix it.

**Comment by RaitaroH** [comment]
BTW, you know how is easy is to fix something when the devs write nice, logical css? You sure do.

Also, would be awesome to integrate this theme in stylus. Maybe just as an option.
I can edit it so it has option arrays instead of individual theme picking. So would be easier to change the themes around in one click. I don't do that because I want to cp/paste easily on userstyles. I can make a special case for stylus if you would like.

**Comment by Mottie** [comment]
I remember the idea about including a theme has been brought up before. It was decided that users could use the plugin to style itself, so there was no need to add an internal theme.

Is that still the general thought on this @tophf?

**Comment by Mottie** [comment]
Hmm, actually that fix doesn't work. Now for other color values (hex, rgb(a) and hsl(a)) the swatches are inverted. These swatches should all have the same color:

![](https://user-images.githubusercontent.com/136959/33143397-60125154-cf7f-11e7-9d37-993e201e580f.png)

```css
body {
    background: navy !important;
    color: #000080 !important;
    border-color: rgb(0, 0, 128) !important;
    box-shadow: 1px 1px hsl(240, 100%, 25%) !important;
}
```

**Comment by RaitaroH** [comment]
Yes I think so.
Also, damn. Let me just remove the filtering entirely.

**Comment by RaitaroH** [comment]
Ok so. I either break color picking, or I have !important look blue instead.

**Comment by RaitaroH** [comment]
Now I'm sure it's fixed. The only 2 things:
> the color is a bit darker because of an opacity setting. I will leave it as it is.
> the `!important` now are not orange anymore

![screenshot from 2017-11-22 20 41 48](https://user-images.githubusercontent.com/19552720/33144454-c1c79b70-cfc5-11e7-9872-8d8194bb9b6e.png)

**Comment by Mottie** [comment]
I think if you add a `:not(.cm-colorview)` to the keyword and remove the filter invert targeting the swatch, it'll fix it:

```css
.cm-s-default span.cm-keyword:not(.cm-colorview), .cm-s-default span.cm-string {
  color: var(--main-color);
  filter: hue-rotate(60deg);
}
.cm-s-default span.cm-link, .cm-s-default span.cm-keyword:not(.cm-colorview) {
  color: var(--main-color);
  filter: invert(100%);
}
/*
.codemirror-colorview-background  {
  filter: invert(100%) !important;
}
*/
```

Edit: Tested and it works 😸 

EDIT RaitaroH: Nice, then. Enjoy the theme ;)

**Comment by RaitaroH** [comment]
Pff... had too much to do today huh?
Thanks now it works perfectly.

![screenshot from 2017-11-22 20 49 56](https://user-images.githubusercontent.com/19552720/33144763-c2223ca0-cfc6-11e7-8e1b-7f50b685addf.png)

**Comment by RaitaroH** [comment]
So, it's alright now right?

**Comment by RaitaroH** [comment]
Cus if I kinda wanna call it a day. I am really tired.

**Comment by Mottie** [comment]
Sorta... when I switch the CodeMirror theme, a white background shows up:

This is added when I switch to the base-16-light theme.

```css
.cm-s-base16-light.CodeMirror {
  background: #f5f5f5;
  color: #202020;
}
```

The swatches are perfect though!
