### ISSUE TITLE
Disabled styles in popup

### ISSUE THREAD

**Issue by Mottie** [RaitaroH/Stylus-DeepDark#18]
- [x] First off the disabled styles in the popup are now too dim (from https://github.com/RaitaroH/Stylus-DeepDark/commit/ef8c77e93a62a6f45a60056d102982c7c15d5bab).

- [x] Second, if I'm using the <kbd>tab</kbd> key inside the popup, the style doesn't brighten as it does while hovering over the entry with a mouse.

![dev](https://user-images.githubusercontent.com/136959/41036362-6f79a71c-6955-11e8-82b5-f5dfa6160422.gif)

This can be solved by using the [`:focus-within`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within) selector.

```css
#installed .entry.disabled:focus-within .style-name {
  color: var(--main-text) !important;
}
```

- [x] Thirdly, hovering over the controls of a disabled entry should also brighten the disabled entry name.
