### ISSUE TITLE
stylus-deepdark issues with non-styled codemirror background

### ISSUE THREAD

**Issue by the-j0k3r** [RaitaroH/Stylus-DeepDark#21]
This is a head scratcher, I noticed this when writing styles in Stylus-DeepDark and this one of the reasons why I [reverted](a66c204) https://github.com/RaitaroH/Stylus-DeepDark/commit/f9d5afc5fbbb0b4b37d75a4fcc81de799f665680

The issue is exposed in two distinct ways.

1) Writing a new style

![posts-marked-read-when-they-wrent](https://user-images.githubusercontent.com/31389848/41051746-df203f96-69ae-11e8-99fa-7bd4aa35e924.gif)

You can see that the Codemirror background is initially LIGHTER this is wack probably even my fault but wack none-the-less

2) When enabling 
```css
	.cm-searching:after
	{
		content: "" !important;
		height: 1px !important;
		background: var(--main-color) !important;
		position: absolute !important;
		width: 100% !important;
		margin-top: 17px!important;
	}
 ```
First IDK where the **horizontal scrollbar** is coming from by enabling the CSS above. Its dumb, there's no code going that far into right anywhere in this style since 0c3b94f562a3d3b4

But here it is again

![posts-marked-read-when-they-wrent](https://user-images.githubusercontent.com/31389848/41052242-2a1977f0-69b0-11e8-8774-141bd215eca0.gif)

Ill try and see if I can fix this but the horizontal scrollbar is killing me also.
